import os
from io import BytesIO
import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

# Helper for coloring DOCX table cells
def set_cell_background(cell, hex_color):
    shading_xml = f'<w:shd {nsdecls("w")} w:fill="{hex_color}"/>'
    cell._tc.get_or_add_tcPr().append(parse_xml(shading_xml))

_SUPERSCRIPT_DIGITS = str.maketrans("0123456789", "⁰¹²³⁴⁵⁶⁷⁸⁹")

def format_delta_order(raw):
    """
    solve_newton_forward/backward return delta_order as e.g. 'y₀', 'Δy₀',
    'Δ^2y₀', 'Δ^3y₀' — caret notation for order >= 2, not a display-ready
    unicode superscript. Convert '^N' -> unicode superscript digits so it
    renders correctly in exported tables.
    """
    if "^" not in raw:
        return raw
    base, _, rest = raw.partition("^")
    # rest looks like "2y₀" -- split the leading digits from the trailing label
    digits = ""
    i = 0
    while i < len(rest) and rest[i].isdigit():
        digits += rest[i]
        i += 1
    return base + digits.translate(_SUPERSCRIPT_DIGITS) + rest[i:]

def get_variable_labels(result_data):
    """
    Returns (independent_label, dependent_label) for table/text headers,
    falling back to 'x'/'y' when the result has no variable_labels field
    (the common case today). Purely additive -- does not affect the solve,
    only how the export is labeled.
    """
    labels = result_data.get("variable_labels") or {}
    return labels.get("independent", "x"), labels.get("dependent", "y")

def generate_docx(result_data):
    """
    Generates a beautifully styled Word document with tables and formatting
    for the numerical method solution.
    """
    doc = docx.Document()
    
    # Page setup
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
        
    # Styles
    styles = doc.styles
    normal_style = styles['Normal']
    normal_style.font.name = 'Segoe UI'
    normal_style.font.size = Pt(11)
    
    # Title
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT
    title_run = title.add_run(f"Solution Report: {result_data.get('method', 'Numerical Solution')}")
    title_run.font.name = 'Segoe UI'
    title_run.font.size = Pt(20)
    title_run.bold = True
    title_run.font.color.rgb = RGBColor(37, 99, 235) # Premium blue color
    
    # Subtitle or basic info
    doc.add_paragraph("Generated by Numerical Methods Solver API.")
    doc.add_paragraph().add_run("Problem Summary:").bold = True
    
    summary_paragraph = doc.add_paragraph()
    if "equation" in result_data:
        summary_paragraph.add_run(f"Equation: ").bold = True
        summary_paragraph.add_run(f"{result_data['equation']}\n")
    if "ode" in result_data:
        summary_paragraph.add_run(f"ODE: ").bold = True
        summary_paragraph.add_run(f"{result_data['ode']}\n")
    if "root" in result_data:
        summary_paragraph.add_run(f"Calculated Root: ").bold = True
        summary_paragraph.add_run(f"{result_data['root']:.8f}\n")
    if "interpolated_y" in result_data:
        x_label, y_label = get_variable_labels(result_data)
        summary_paragraph.add_run(f"Interpolated {y_label} at {x_label}={result_data['target_x']}: ").bold = True
        summary_paragraph.add_run(f"{result_data['interpolated_y']:.8f}\n")
    if result_data.get("method") == "Newton's Forward Difference Formula":
        summary_paragraph.add_run(f"Step size (h): ").bold = True
        summary_paragraph.add_run(f"{result_data['h']:.6f}\n")
        summary_paragraph.add_run(f"U = (x − x₀) / h: ").bold = True
        summary_paragraph.add_run(f"{result_data['s']:.6f}\n")
    if result_data.get("method") == "Newton's Backward Difference Formula":
        summary_paragraph.add_run(f"Step size (h): ").bold = True
        summary_paragraph.add_run(f"{result_data['h']:.6f}\n")
        summary_paragraph.add_run(f"V = (x − xₙ) / h: ").bold = True
        summary_paragraph.add_run(f"{result_data['s']:.6f}\n")
    if "integral" in result_data:
        summary_paragraph.add_run(f"Calculated Integral: ").bold = True
        summary_paragraph.add_run(f"{result_data['integral']:.8f}\n")
    if "final_y" in result_data:
        summary_paragraph.add_run(f"Final Value of y({result_data.get('xn')}): ").bold = True
        summary_paragraph.add_run(f"{result_data['final_y']:.8f}\n")
        
    doc.add_paragraph().add_run("Step-by-Step Iterations:").bold = True
    
    # Create tables based on method
    steps = result_data.get("steps", [])
    if not steps:
        doc.add_paragraph("No detailed steps available.")
    else:
        # Determine columns based on steps fields
        sample_step = steps[0]
        
        # We can extract keys and format them
        if "iteration" in sample_step:  # Root finding
            if "fa" in sample_step:  # Bracket methods
                headers = ["Iteration", "a", "b", "c", "f(a)", "f(b)", "f(c)", "Error"]
                keys = ["iteration", "a", "b", "c", "fa", "fb", "fc", "error"]
            elif "df_xi" in sample_step:  # Newton-Raphson
                headers = ["Iteration", "xi", "f(xi)", "f'(xi)", "xi+1", "Error"]
                keys = ["iteration", "xi", "f_xi", "df_xi", "xi_next", "error"]
            else:  # Secant
                headers = ["Iteration", "x_prev", "x_curr", "x_next", "f(x_next)", "Error"]
                keys = ["iteration", "x_prev", "x_curr", "x_next", "f_next", "error"]
        elif "x_val" in sample_step:  # Lagrange interpolation terms
            headers = ["i", "x_i", "y_i", "Numerator Term", "Denominator Term", "L_i(x)", "Contribution"]
            keys = ["index", "x_val", "y_val", "formula_num", "formula_den", "term_value", "contribution"]
        elif "slope" in sample_step:  # Euler ODE
            headers = ["Step", "x", "y", "dy/dx (Slope)", "dy (h * Slope)", "Next x", "Next y"]
            keys = ["step", "x", "y", "slope", "dy", "next_x", "next_y"]
        elif "k1" in sample_step:  # RK4 ODE
            headers = ["Step", "x", "y", "k1", "k2", "k3", "k4", "Next y"]
            keys = ["step", "x", "y", "k1", "k2", "k3", "k4", "next_y"]
        elif "index" in sample_step:  # Integration steps
            headers = ["Index", "x_i", "y_i"]
            keys = ["index", "x", "y"]
        elif "delta_order" in sample_step:  # Newton Forward/Backward Difference terms
            headers = ["k", "Term", "Difference Value", "U-product", "k!", "Contribution"]
            keys = ["term_index", "delta_order", "delta_value", "s_product", "factorial", "contribution"]
        else:
            # Fallback
            keys = list(sample_step.keys())
            headers = [k.capitalize() for k in keys]
            
        table = doc.add_table(rows=1, cols=len(headers))
        table.style = 'Light Shading Accent 1'
        
        # Style headers
        hdr_cells = table.rows[0].cells
        for col_idx, header_text in enumerate(headers):
            hdr_cells[col_idx].text = header_text
            hdr_cells[col_idx].paragraphs[0].runs[0].font.bold = True
            hdr_cells[col_idx].paragraphs[0].runs[0].font.color.rgb = RGBColor(255, 255, 255)
            set_cell_background(hdr_cells[col_idx], "2563EB")  # Primary blue
            
        # Add values
        for idx, step in enumerate(steps):
            row_cells = table.add_row().cells
            for col_idx, key in enumerate(keys):
                val = step.get(key, "")
                if key == "delta_order" and isinstance(val, str):
                    formatted_val = format_delta_order(val)
                elif isinstance(val, float):
                    formatted_val = f"{val:.6f}"
                elif isinstance(val, int):
                    formatted_val = str(val)
                else:
                    formatted_val = str(val)
                row_cells[col_idx].text = formatted_val
                
                # Alternate row shading
                if idx % 2 == 1:
                    set_cell_background(row_cells[col_idx], "F3F4F6") # Light gray
                    
    # Newton's divided difference has a matrix table parameter
    if "table" in result_data and result_data.get("method") == "Newton's Divided Difference":
        doc.add_paragraph().add_run("\nDivided Difference Table:").bold = True
        dd_table_data = result_data["table"]
        n_pts = len(dd_table_data)
        
        # Headers: x, y, dd1, dd2, ...
        dd_headers = ["x", "y"] + [f"f[{','.join(['x']*i)}]" for i in range(1, n_pts)]
        table = doc.add_table(rows=1, cols=len(dd_headers))
        table.style = 'Light Shading Accent 1'
        
        hdr_cells = table.rows[0].cells
        for col_idx, header_text in enumerate(dd_headers):
            hdr_cells[col_idx].text = header_text
            hdr_cells[col_idx].paragraphs[0].runs[0].font.bold = True
            hdr_cells[col_idx].paragraphs[0].runs[0].font.color.rgb = RGBColor(255, 255, 255)
            set_cell_background(hdr_cells[col_idx], "2563EB")
            
        for row_idx, row_vals in enumerate(dd_table_data):
            row_cells = table.add_row().cells
            for col_idx, val in enumerate(row_vals):
                if val is None:
                    row_cells[col_idx].text = ""
                elif isinstance(val, float):
                    row_cells[col_idx].text = f"{val:.6f}"
                else:
                    row_cells[col_idx].text = str(val)
                
                if row_idx % 2 == 1:
                    set_cell_background(row_cells[col_idx], "F3F4F6")

    # Newton's Forward/Backward Difference has a difference table (Δ or ∇)
    if "difference_table" in result_data and result_data.get("method") in (
        "Newton's Forward Difference Formula",
        "Newton's Backward Difference Formula",
    ):
        x_label, y_label = get_variable_labels(result_data)
        doc.add_paragraph().add_run("\nDifference Table:").bold = True
        diff_rows = result_data["difference_table"]
        n_pts = len(diff_rows)

        op = "Δ" if result_data["method"].startswith("Newton's Forward") else "∇"
        key_prefix = "delta_" if op == "Δ" else "nabla_"
        order_count = max(len(row) - 2 for row in diff_rows) if diff_rows else 0
        diff_headers = [x_label, y_label] + [
            f"{op}{str(j).translate(_SUPERSCRIPT_DIGITS) if j > 1 else ''}{y_label}"
            for j in range(1, order_count + 1)
        ]

        table = doc.add_table(rows=1, cols=len(diff_headers))
        table.style = 'Light Shading Accent 1'

        hdr_cells = table.rows[0].cells
        for col_idx, header_text in enumerate(diff_headers):
            hdr_cells[col_idx].text = header_text
            hdr_cells[col_idx].paragraphs[0].runs[0].font.bold = True
            hdr_cells[col_idx].paragraphs[0].runs[0].font.color.rgb = RGBColor(255, 255, 255)
            set_cell_background(hdr_cells[col_idx], "2563EB")

        for row_idx, row in enumerate(diff_rows):
            row_cells = table.add_row().cells
            row_cells[0].text = f"{row['x']:.6f}"
            row_cells[1].text = f"{row['y']:.6f}"
            for j in range(1, order_count + 1):
                val = row.get(f"{key_prefix}{j}")
                row_cells[j + 1].text = "" if val is None else f"{val:.6f}"

            if row_idx % 2 == 1:
                for cell in row_cells:
                    set_cell_background(cell, "F3F4F6")

    file_stream = BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream

def generate_pdf(result_data):
    """
    Generates a beautifully styled PDF document with tables and formatting
    for the numerical method solution using ReportLab.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        name='DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#2563EB'),
        spaceAfter=15
    )
    
    h2_style = ParagraphStyle(
        name='SectionHeader',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#1E3A8A'),
        spaceBefore=15,
        spaceAfter=8
    )
    
    body_style = ParagraphStyle(
        name='BodyTextCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        spaceAfter=6
    )
    
    bold_body_style = ParagraphStyle(
        name='BoldBody',
        parent=body_style,
        fontName='Helvetica-Bold'
    )
    
    table_header_style = ParagraphStyle(
        name='TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=11,
        textColor=colors.white
    )
    
    table_body_style = ParagraphStyle(
        name='TableBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=10
    )
    
    story = []
    
    # Title
    story.append(Paragraph(f"Solution Report: {result_data.get('method', 'Numerical Solution')}", title_style))
    story.append(Paragraph("Generated by Numerical Methods Solver API.", body_style))
    story.append(Spacer(1, 10))
    
    # Problem summary
    story.append(Paragraph("Problem Summary", h2_style))
    
    summary_text = ""
    if "equation" in result_data:
        summary_text += f"<b>Equation:</b> {result_data['equation']}<br/>"
    if "ode" in result_data:
        summary_text += f"<b>ODE:</b> {result_data['ode']}<br/>"
    if "root" in result_data:
        summary_text += f"<b>Calculated Root:</b> {result_data['root']:.8f}<br/>"
    if "interpolated_y" in result_data:
        x_label, y_label = get_variable_labels(result_data)
        summary_text += f"<b>Interpolated {y_label} at {x_label}={result_data['target_x']}:</b> {result_data['interpolated_y']:.8f}<br/>"
    if result_data.get("method") == "Newton's Forward Difference Formula":
        summary_text += f"<b>Step size (h):</b> {result_data['h']:.6f}<br/>"
        summary_text += f"<b>U = (x &#8722; x&#8320;) / h:</b> {result_data['s']:.6f}<br/>"
    if result_data.get("method") == "Newton's Backward Difference Formula":
        summary_text += f"<b>Step size (h):</b> {result_data['h']:.6f}<br/>"
        summary_text += f"<b>V = (x &#8722; x&#8345;) / h:</b> {result_data['s']:.6f}<br/>"
    if "integral" in result_data:
        summary_text += f"<b>Calculated Integral:</b> {result_data['integral']:.8f}<br/>"
    if "final_y" in result_data:
        summary_text += f"<b>Final Value of y({result_data.get('xn')}):</b> {result_data['final_y']:.8f}<br/>"
        
    story.append(Paragraph(summary_text, body_style))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph("Detailed Steps / Iterations", h2_style))
    
    steps = result_data.get("steps", [])
    if not steps:
        story.append(Paragraph("No detailed steps available.", body_style))
    else:
        # Determine table keys and headers
        sample_step = steps[0]
        if "iteration" in sample_step:
            if "fa" in sample_step:
                headers = ["Iter", "a", "b", "c", "f(a)", "f(b)", "f(c)", "Error"]
                keys = ["iteration", "a", "b", "c", "fa", "fb", "fc", "error"]
            elif "df_xi" in sample_step:
                headers = ["Iter", "xi", "f(xi)", "f'(xi)", "xi+1", "Error"]
                keys = ["iteration", "xi", "f_xi", "df_xi", "xi_next", "error"]
            else:
                headers = ["Iter", "x_prev", "x_curr", "x_next", "f(x_next)", "Error"]
                keys = ["iteration", "x_prev", "x_curr", "x_next", "f_next", "error"]
        elif "x_val" in sample_step:
            headers = ["i", "x_i", "y_i", "Formula Numerator", "Formula Denominator", "L_i(x)", "Contrib"]
            keys = ["index", "x_val", "y_val", "formula_num", "formula_den", "term_value", "contribution"]
        elif "slope" in sample_step:
            headers = ["Step", "x", "y", "dy/dx", "dy", "Next x", "Next y"]
            keys = ["step", "x", "y", "slope", "dy", "next_x", "next_y"]
        elif "k1" in sample_step:
            headers = ["Step", "x", "y", "k1", "k2", "k3", "k4", "Next y"]
            keys = ["step", "x", "y", "k1", "k2", "k3", "k4", "next_y"]
        elif "index" in sample_step:
            headers = ["Index", "x_i", "y_i"]
            keys = ["index", "x", "y"]
        elif "delta_order" in sample_step:  # Newton Forward/Backward Difference terms
            headers = ["k", "Term", "Difference Value", "U-product", "k!", "Contribution"]
            keys = ["term_index", "delta_order", "delta_value", "s_product", "factorial", "contribution"]
        else:
            keys = list(sample_step.keys())
            headers = [k.capitalize() for k in keys]
            
        # Compile table data
        table_data = []
        # Header Row
        table_data.append([Paragraph(h, table_header_style) for h in headers])
        
        # Body Rows
        for step in steps:
            row = []
            for k in keys:
                val = step.get(k, "")
                if k == "delta_order" and isinstance(val, str):
                    formatted_val = format_delta_order(val)
                elif isinstance(val, float):
                    formatted_val = f"{val:.5f}"
                elif isinstance(val, int):
                    formatted_val = str(val)
                else:
                    formatted_val = str(val)
                row.append(Paragraph(formatted_val, table_body_style))
            table_data.append(row)
            
        # Create PDF Table
        # Make sure column widths fit nicely
        col_width = (doc.width) / len(headers)
        t = Table(table_data, colWidths=[col_width]*len(headers))
        
        t_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563EB')),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
            ('TOPPADDING', (0, 0), (-1, 0), 6),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E7EB')),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#D1D5DB')),
        ])
        
        # Alternating row backgrounds
        for row_idx in range(1, len(table_data)):
            if row_idx % 2 == 1:
                t_style.add('BACKGROUND', (0, row_idx), (-1, row_idx), colors.HexColor('#F9FAFB'))
            else:
                t_style.add('BACKGROUND', (0, row_idx), (-1, row_idx), colors.white)
                
        t.setStyle(t_style)
        story.append(t)
        
    # Newton's divided difference specific table
    if "table" in result_data and result_data.get("method") == "Newton's Divided Difference":
        story.append(Spacer(1, 10))
        story.append(Paragraph("Divided Difference Table", h2_style))
        dd_table_data = result_data["table"]
        n_pts = len(dd_table_data)
        dd_headers = ["x", "y"] + [f"f[{','.join(['x']*i)}]" for i in range(1, n_pts)]
        
        table_data = []
        table_data.append([Paragraph(h, table_header_style) for h in dd_headers])
        
        for row_vals in dd_table_data:
            row = []
            for val in row_vals:
                if val is None:
                    row.append(Paragraph("", table_body_style))
                elif isinstance(val, float):
                    row.append(Paragraph(f"{val:.5f}", table_body_style))
                else:
                    row.append(Paragraph(str(val), table_body_style))
            table_data.append(row)
            
        col_width = (doc.width) / len(dd_headers)
        t = Table(table_data, colWidths=[col_width]*len(dd_headers))
        
        t_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563EB')),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
            ('TOPPADDING', (0, 0), (-1, 0), 6),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E7EB')),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#D1D5DB')),
        ])
        
        for row_idx in range(1, len(table_data)):
            if row_idx % 2 == 1:
                t_style.add('BACKGROUND', (0, row_idx), (-1, row_idx), colors.HexColor('#F9FAFB'))
            else:
                t_style.add('BACKGROUND', (0, row_idx), (-1, row_idx), colors.white)
                
        t.setStyle(t_style)
        story.append(t)

    # Newton's Forward/Backward Difference has a difference table (Δ or ∇)
    if "difference_table" in result_data and result_data.get("method") in (
        "Newton's Forward Difference Formula",
        "Newton's Backward Difference Formula",
    ):
        x_label, y_label = get_variable_labels(result_data)
        story.append(Spacer(1, 10))
        story.append(Paragraph("Difference Table", h2_style))
        diff_rows = result_data["difference_table"]

        op = "&#916;" if result_data["method"].startswith("Newton's Forward") else "&#8711;"
        key_prefix = "delta_" if result_data["method"].startswith("Newton's Forward") else "nabla_"
        order_count = max(len(row) - 2 for row in diff_rows) if diff_rows else 0
        diff_headers = [x_label, y_label] + [
            f"{op}{str(j).translate(_SUPERSCRIPT_DIGITS) if j > 1 else ''}{y_label}"
            for j in range(1, order_count + 1)
        ]

        table_data = []
        table_data.append([Paragraph(h, table_header_style) for h in diff_headers])

        for row in diff_rows:
            cells = [Paragraph(f"{row['x']:.5f}", table_body_style), Paragraph(f"{row['y']:.5f}", table_body_style)]
            for j in range(1, order_count + 1):
                val = row.get(f"{key_prefix}{j}")
                cells.append(Paragraph("" if val is None else f"{val:.5f}", table_body_style))
            table_data.append(cells)

        col_width = (doc.width) / len(diff_headers)
        t = Table(table_data, colWidths=[col_width] * len(diff_headers))

        t_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563EB')),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
            ('TOPPADDING', (0, 0), (-1, 0), 6),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E7EB')),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#D1D5DB')),
        ])

        for row_idx in range(1, len(table_data)):
            if row_idx % 2 == 1:
                t_style.add('BACKGROUND', (0, row_idx), (-1, row_idx), colors.HexColor('#F9FAFB'))
            else:
                t_style.add('BACKGROUND', (0, row_idx), (-1, row_idx), colors.white)

        t.setStyle(t_style)
        story.append(t)

    doc.build(story)
    buffer.seek(0)
    return buffer